name: CSV to XML Converter

on:
  schedule:
    - cron: '0 * * * *'  # Spustí každou hodinu

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml

    - name: Convert CSV to XML
      run: |
        python csv_to_xml/csv_to_xml.py  # Změna cesty podle umístění vašeho skriptu

    - name: Upload XML to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './'  # Tady zůstává, pokud ukládáte soubor v kořeni
        publish_branch: main  # Branch pro GitHub Pages
